apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogJ2lzdGlvZCcKICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgLSByb2xlOiBlbmRwb2ludHMKICAgIG5hbWVzcGFjZXM6CiAgICAgIG5hbWVzOgogICAgICAtIGlzdGlvLXN5c3RlbQogIHJlbGFiZWxfY29uZmlnczoKICAtIHNvdXJjZV9sYWJlbHM6IFtfX21ldGFfa3ViZXJuZXRlc19zZXJ2aWNlX25hbWUsIF9fbWV0YV9rdWJlcm5ldGVzX2VuZHBvaW50X3BvcnRfbmFtZV0KICAgIGFjdGlvbjoga2VlcAogICAgcmVnZXg6IGlzdGlvZDtodHRwLW1vbml0b3JpbmcKLSBqb2JfbmFtZTogJ2Vudm95LXN0YXRzJwogIG1ldHJpY3NfcGF0aDogL3N0YXRzL3Byb21ldGhldXMKICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgLSByb2xlOiBwb2QKICByZWxhYmVsX2NvbmZpZ3M6CiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfcG9kX2NvbnRhaW5lcl9wb3J0X25hbWVdCiAgICBhY3Rpb246IGtlZXAKICAgIHJlZ2V4OiAnLiotZW52b3ktcHJvbSc=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
